elemento('H', hidrogeno).
elemento('Li', litio).
elemento('Na', sodio).
elemento('K', potasio).
elemento('Rb', rubidio).
elemento('Cs', cesio).
elemento('Fr', francio).
elemento('Be', berilio).
elemento('Mg', magnesio).
elemento('Ca', calcio).
elemento('Sr', estroncio).
elemento('Ba', bario).
elemento('Ra', radio).
elemento('Sc', escandio).
elemento('Y', itrio).
elemento('Lu', lutencio).
elemento('Lr', laurencio).
elemento('Ti', titanio).
elemento('V', vanadio).
elemento('Cr', cromo).
elemento('Mn', manganeso).
elemento('Fe', hierro).
elemento('Ru', rutenio).
elemento('Co', cobalto).
elemento('Rh', rodio).
elemento('Ni', niquel).
elemento('Cu', cobre).
elemento('Ag', plata).
elemento('Zn', zinc).
elemento('Cd', cadmio).
elemento('B', boro).
elemento('Al', aluminio).
elemento('Ga', galio).
elemento('In', idio).
elemento('Tl', talio).
elemento('C', carbono).
elemento('Si', silicio).
elemento('Ge', germanio).
elemento('Sn', estaño).
elemento('Pb', plomo).
elemento('N', nitrogeno).
elemento('P', fosforo).
elemento('As', arsenico).
elemento('Sb', antimonio).
elemento('Bi', bismuto).
elemento('O', oxigeno).
elemento('S', azufre).
elemento('Se', selenio).
elemento('Te', telurio).
elemento('Po', polonio).
elemento('F', fluor).
elemento('Cl', cloro).
elemento('Br', bromo).
elemento('I', yodo).
elemento('At', astato).
elemento('He', helio).
elemento('Ne', neon).
elemento('Ar', argon).
elemento('Kr', kripton).
elemento('Xe', xenon).
elemento('Rn', radon).
