elemento('H', hidrogeno).
elemento('Li', litio).
elemento('Na', sodio).
elemento('K', potasio).
elemento('Rb', rubidio).
elemento('Cs', cesio).
elemento('Fr', francio).
elemento('Be', berilio).
elemento('Mg', magnesio).
elemento('Ca', calcio).
elemento('Sr', estroncio).
elemento('Ba', bario).
elemento('Ra', radio).
elemento('Sc', escandio).
elemento('Y', itrio).
elemento('Lu', lutencio).
elemento('Lr', laurencio).
elemento('Ti', titanio).
elemento('V', vanadio).
elemento('Cr', cromo).
elemento('Mn', manganeso).

elemento('Fe', hierro).
elemento('').
elemento('Ba', bario).
elemento('Ra', radio).
elemento('Sc', escandio).
elemento('Y', itrio).
elemento('Lu', lutencio).
elemento('Lr', laurencio).
elemento('Ti', titanio).
elemento('V', vanadio).
elemento('Cr', cromo).
elemento('Mn', manganeso).
elemento('Ca', calcio).
elemento('Sr', estroncio).
elemento('Ba', bario).
elemento('Ra', radio).
elemento('Sc', escandio).
elemento('Y', itrio).
elemento('Lu', lutencio).